# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aggregator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61ggregator.proto\" \n\rClientRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"C\n\x0eStockAggUpdate\x12\x0f\n\x07\x63ompany\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x11\n\ttimestamp\x18\x03 \x01(\t2?\n\nAggregator\x12\x31\n\x0cGetStockData\x12\x0e.ClientRequest\x1a\x0f.StockAggUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aggregator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CLIENTREQUEST']._serialized_start=20
  _globals['_CLIENTREQUEST']._serialized_end=52
  _globals['_STOCKAGGUPDATE']._serialized_start=54
  _globals['_STOCKAGGUPDATE']._serialized_end=121
  _globals['_AGGREGATOR']._serialized_start=123
  _globals['_AGGREGATOR']._serialized_end=186
# @@protoc_insertion_point(module_scope)
