# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stockdata.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstockdata.proto\"\x1f\n\x0cStockRequest\x12\x0f\n\x07\x63ompany\x18\x01 \x01(\t\"@\n\x0bStockUpdate\x12\x0f\n\x07\x63ompany\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x11\n\ttimestamp\x18\x03 \x01(\t2C\n\x10StockDataService\x12/\n\x0eGetStockPrices\x12\r.StockRequest\x1a\x0c.StockUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stockdata_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_STOCKREQUEST']._serialized_start=19
  _globals['_STOCKREQUEST']._serialized_end=50
  _globals['_STOCKUPDATE']._serialized_start=52
  _globals['_STOCKUPDATE']._serialized_end=116
  _globals['_STOCKDATASERVICE']._serialized_start=118
  _globals['_STOCKDATASERVICE']._serialized_end=185
# @@protoc_insertion_point(module_scope)
